In [33]:
from sqlalchemy import create_engine
from sqlalchemy.engine import URL
import pandas as pd

import datetime
from sqlalchemy.orm import Session
from sqlalchemy import Table, Column, Integer, String, MetaData, BIGINT, ForeignKey
from sqlalchemy.types import DateTime
from sqlalchemy.types import Integer, Float, String, JSON, DateTime, BINARY, LargeBinary,Boolean
from pangres import upsert
from sqlalchemy.orm import declarative_base, relationship

## Connecting Mysql database

In [34]:
connection_url_mysql = URL.create(
  'mysql+pymysql',
  username='root',
  password='spts@3311',
  host='10.0.0.9',
  port=3306,
  database='sooperwizer'
)
engine_mysql = create_engine(connection_url_mysql)
# engine.connect()
session_mysql = Session(engine_mysql, future=True)

## Connecting Postgres database

In [35]:
connection_url_postgres = URL.create(
  'postgresql+psycopg2',
  username='postgres',
  password='spts@3311',
  host='10.0.0.9',
  port=5432,
  database='postgres'
)
engine_postgres = create_engine(connection_url_postgres)
# engine.connect()
session_postgres = Session(engine_postgres, future=True)

In [36]:
print(engine_mysql)
print(engine_postgres)

Engine(mysql+pymysql://root:***@10.0.0.9:3306/sooperwizer)
Engine(postgresql+psycopg2://postgres:***@10.0.0.9:5432/postgres)

In [37]:
# session_postgres.execute("select * from public.bundle_scan limit 1").all()

In [38]:
# session_postgres.execute("select version()").all()

## Importing tables

In [39]:
piece_wise_scan = session_mysql.execute("select * from piece_wise_scan").all()
piece_wise_cut_report = session_mysql.execute("select * from piece_wise_cut_report").all()
cut_report = session_mysql.execute("select * from cut_report").all()
cut_job = session_mysql.execute("select * from cut_job").all()
production_order = session_mysql.execute("select * from production_order").all()
sale_order = session_mysql.execute("select * from sale_order").all()
style_template = session_mysql.execute("select * from style_template").all()
marker = session_mysql.execute("select * from marker").all()

worker_scan = session_mysql.execute("select * from worker_scan").all()
line = session_mysql.execute("select * from line").all()
worker = session_mysql.execute("select * from worker").all()
machine = session_mysql.execute("select * from machine").all()

operation = session_mysql.execute("select * from operation").all()
section  = session_mysql.execute("select * from section").all()
machine_type = session_mysql.execute("select * from machine_type").all()

scan = session_mysql.execute("select * from scan").all()

module = session_mysql.execute("select * from module").all()
userpermission = session_mysql.execute("select * from userpermission").all()

style_bulletin = session_mysql.execute("select * from style_bulletin")
tag = session_mysql.execute("select * from tag")
user = session_mysql.execute("select * from user")

## pandas Dataframes

In [40]:
machine_table = pd.DataFrame(machine, columns=['MachineID', 'MachineCode', 'MachineDescription', 'MachineImageUrl','MachineThumbnailUrl', 'MachineTypeID', 'ActiveWorkerID', 'LineID', 'Operations', 'CreatedAt', 'UpdatedAt','BoxID'])
machine_table = machine_table.astype({'MachineID':'Int64','MachineCode':'string','MachineDescription':'string', 'MachineImageUrl':'string', 'MachineThumbnailUrl':'string','MachineTypeID':'Int64','ActiveWorkerID':'Int64','LineID':'Int64','CreatedAt':'datetime64[ns]', 'UpdatedAt':'datetime64[ns]','BoxID':'Int64'})
machine_table["Operations"] = machine_table["Operations"].to_json()

piece_wise_scan_table = pd.DataFrame(piece_wise_scan, columns=['PieceWiseScanningID', 'ScanID', 'BundleID', 'PieceID', 'OperationID', 'WorkerID', 'LineID', 'MachineID', 'CreatedAt', 'UpdatedAt'])
piece_wise_scan_table = piece_wise_scan_table.astype({'PieceWiseScanningID':'Int64', 'ScanID':'int64', 'BundleID':'Int64', 'PieceID':'Int64', 'OperationID':'Int64', 'WorkerID':'Int64', 'LineID':'Int64', 'MachineID':'Int64', 'CreatedAt':'datetime64[ns]', 'UpdatedAt':'datetime64[ns]'})

scan_table = pd.DataFrame(scan, columns=['ScanID', 'WorkerScanID', 'BundleID','PieceID', 'OperationID', 'WorkerID', 'LineID', 'MachineID', 'ShortAddress', 'LongAddress', 'HostIP', 'CreatedAt', 'UpdatedAt'])
scan_table = scan_table.astype({"ScanID":'Int64', 'WorkerScanID':'Int64', 'BundleID':'Int64', 'PieceID':'Int64', 'OperationID':'Int64', 'WorkerID':'Int64', 'LineID':'Int64', 'MachineID':'Int64', 'ShortAddress':'string', 'LongAddress':'string', 'HostIP':'string', 'CreatedAt':'datetime64[ns]', 'UpdatedAt':'datetime64[ns]'})

worker_scan_table = pd.DataFrame(worker_scan, columns=['WorkerScanID', 'WorkerID', 'LineID', 'MachineID', 'WorkerOperations', 'CreatedAt', 'UpdatedAt','HasExpired','EndedAt'])
worker_scan_table = worker_scan_table.astype({'WorkerScanID':'int64', 'WorkerID':'Int64', 'LineID':'Int64', 'MachineID':'Int64', 'CreatedAt':'datetime64[ns]', 'UpdatedAt':'datetime64[ns]','HasExpired':'Int64','EndedAt':'datetime64[ns]'})
worker_scan_table['WorkerOperations'] = worker_scan_table['WorkerOperations'].to_json()

line_table = pd.DataFrame(line, columns=['LineID', 'LineCode', 'LineDescription', 'CreatedAt', 'UpdatedAt'])
line_table = line_table.astype({'LineID':'Int64', 'LineCode':'string', 'LineDescription':'string', 'CreatedAt':'datetime64[ns]', 'UpdatedAt':'datetime64[ns]'})

worker_table = pd.DataFrame(worker, columns=['WorkerID', 'WorkerCode', 'WorkerDescription','WorkerImageUrl','WorkerThumbnailUrl','AllocatedMachines', 'CreatedAt', 'UpdatedAt'])
worker_table = worker_table.astype({'WorkerID':'Int64', 'WorkerCode':'string', 'WorkerDescription':'string', 'WorkerImageUrl':'string', 'WorkerThumbnailUrl':'string', 'CreatedAt':'datetime64[ns]', 'UpdatedAt':'datetime64[ns]'})
worker_table["AllocatedMachines"] = worker_table["AllocatedMachines"].to_json()

machine_type_table = pd.DataFrame(machine_type, columns=['MachineTypeID', 'MachineTypeCode', 'MachineTypeDescription','Allowance', 'CreatedAt', 'UpdatedAt'])
machine_type_table = machine_type_table.astype({'MachineTypeID':'Int64', 'MachineTypeCode':'string', 'MachineTypeDescription':'string','CreatedAt':'datetime64[ns]', 'UpdatedAt':'datetime64[ns]','Allowance':'float'})

operation_table = pd.DataFrame(operation, columns=['OperationID', 'OperationCode', 'OperationName', 'OperationDescription', 'Department', 'PieceRate','OperationType', 'OperationImageUrl', 'OperationThumbnailUrl', 'SectionID', 'CreatedAt', 'UpdatedAt'])
operation_table = operation_table.astype({'OperationID':'Int64', 'OperationCode':'string', 'OperationName':'string', 'OperationDescription':'string', 'Department':'string', 'PieceRate':'Int64', 'OperationType':'string', 'OperationImageUrl':'string', 'OperationThumbnailUrl':'string', 'SectionID':'Int64', 'CreatedAt':'datetime64[ns]', 'UpdatedAt':'datetime64[ns]'})

section_table = pd.DataFrame(section, columns=['SectionID', 'SectionCode', 'SectionDescription','CreatedAt', 'UpdatedAt'])
section_table = section_table.astype({'SectionID':'Int64', 'SectionCode':'string', 'SectionDescription':'string', 'CreatedAt':'datetime64[ns]', 'UpdatedAt':'datetime64[ns]'})

piece_wise_cut_report_table = pd.DataFrame(piece_wise_cut_report, columns=['PieceID', 'BundleID', 'PieceNumber','CreatedAt', 'UpdatedAt'])
piece_wise_cut_report_table = piece_wise_cut_report_table.astype({'PieceID':'Int64', 'BundleID':'Int64', 'PieceNumber':'Int64', 'CreatedAt':'datetime64[ns]', 'UpdatedAt':'datetime64[ns]'})

cut_report_table = pd.DataFrame(cut_report, columns=['BundleID', 'BundleCode', 'BundleQuantity', 'ScannedQuantity', 'RemainingQuantity', 'CutJobID','CreatedAt', 'UpdatedAt'])
cut_report_table = cut_report_table.astype({'BundleID':'Int64', 'BundleCode':'string', 'BundleQuantity':'Int64', 'ScannedQuantity':'Int64', 'RemainingQuantity':'Int64', 'CutJobID':'Int64'})

cut_job_table = pd.DataFrame(cut_job, columns=['CutJobID', 'CutNo', 'ProductionOrderID','CutQuantity', 'MarkerID','CreatedAt', 'UpdatedAt'])
cut_job_table = cut_job_table.astype({'CutJobID':'Int64', 'CutNo':'Int64', 'ProductionOrderID':'Int64', 'CutQuantity':'Int64', 'MarkerID':'Int64', 'CreatedAt':'datetime64[ns]', 'UpdatedAt':'datetime64[ns]'})

marker_table = pd.DataFrame(marker, columns=['MarkerID','MarkerCode', 'ProductionOrderID', 'MarkerMapping','CreatedAt', 'UpdatedAt'])
marker_table = marker_table.astype({'MarkerID':'Int64','MarkerCode':'string', 'ProductionOrderID':'Int64', 'CreatedAt':'datetime64[ns]', 'UpdatedAt':'datetime64[ns]'})
marker_table["MarkerMapping"] = marker_table["MarkerMapping"].to_json()

production_order_table = pd.DataFrame(production_order, columns=['ProductionOrderID','ProductionOrderCode', 'SaleOrderID', 'StyleTemplateID','FollowsOperationSequence','CreatedAt', 'UpdatedAt'])
production_order_table = production_order_table.astype({'ProductionOrderID':'Int64', 'ProductionOrderCode':'string', 'SaleOrderID':'Int64', 'StyleTemplateID':'Int64', 'FollowsOperationSequence':'bool', 'CreatedAt':'datetime64[ns]', 'UpdatedAt':'datetime64[ns]'})

sale_order_table = pd.DataFrame(sale_order, columns=['SaleOrderID', 'SaleOrderCode', 'Customer', 'OrderQuantity','CreatedAt', 'UpdatedAt'])
sale_order_table = sale_order_table.astype({'SaleOrderID':'Int64', 'SaleOrderCode':'string', 'Customer':'string', 'OrderQuantity':'Int64', 'CreatedAt':'datetime64[ns]', 'UpdatedAt':'datetime64[ns]'})

style_template_table = pd.DataFrame(style_template, columns=['StyleTemplateID', 'StyleTemplateCode','CreatedAt', 'UpdatedAt'])
style_template_table = style_template_table.astype({'StyleTemplateID':'Int64', 'StyleTemplateCode':'string', 'CreatedAt':'datetime64[ns]', 'UpdatedAt':'datetime64[ns]'})

module_table = pd.DataFrame(module, columns=['ModuleID', 'ModuleCode', 'CreatedAt', 'UpdatedAt'])
module_table = module_table.astype({'ModuleID':'Int64', 'ModuleCode':'string', 'CreatedAt':'datetime64[ns]', 'UpdatedAt':'datetime64[ns]'})

userpermission_table = pd.DataFrame(userpermission, columns=['UserPermissionID', 'UserID', 'ModuleID','CreatedAt', 'UpdatedAt'])
userpermission_table = userpermission_table.astype({'UserPermissionID':'Int64', 'UserID':'Int64', 'ModuleID':'Int64', 'CreatedAt':'datetime64[ns]', 'UpdatedAt':'datetime64[ns]'})

style_bulletin_table = pd.DataFrame(style_bulletin, columns=['StyleBulletinID', 'StyleTemplateID', 'OperationID','OperationSequence', 'ScanType', 'IsFirst', 'IsLast', 'MachineTypeID','CreatedAt', 'UpdatedAt'])
style_bulletin_table = style_bulletin_table.astype({'StyleBulletinID':'Int64', 'StyleTemplateID':'Int64', 'OperationID':'Int64', 'OperationSequence':'Int64', 'ScanType':'string', 'IsFirst':'bool', 'IsLast':'bool', 'MachineTypeID':'Int64', 'CreatedAt':'datetime64[ns]', 'UpdatedAt':'datetime64[ns]'})

user_table = pd.DataFrame(user, columns=['UserID', 'UserName', 'Password', 'UserType', 'LineID','SectionID','CreatedAt', 'UpdatedAt'])
user_table = user_table.astype({'UserID':'Int64', 'UserName':'string', 'Password':'string', 'UserType':'string', 'LineID':'Int64', 'SectionID':'Int64', 'CreatedAt':'datetime64[ns]', 'UpdatedAt':'datetime64[ns]'})

tag_table = pd.DataFrame(tag, columns=['TagID', 'BundleID', 'CreatedAt', 'UpdatedAt'])
tag_table = tag_table.astype({'TagID':'Int64', 'BundleID':'Int64', 'CreatedAt':'datetime64[ns]', 'UpdatedAt':'datetime64[ns]'})

# Denormalizations

In [41]:
machine_table_denorm = machine_table.merge(line_table, how='left', on='LineID').merge(machine_type_table, how='left',on='MachineTypeID').merge(worker_table, how='left',left_on='ActiveWorkerID', right_on='WorkerID')
machine_table_denorm = machine_table_denorm.drop(["CreatedAt_y", "UpdatedAt_y",'CreatedAt_x', 'UpdatedAt_x',], axis=1)
# machine_table_denorm = machine_table_denorm.rename({'CreatedAt_x':'CreatedAt', 'UpdatedAt_x':'UpdatedAt'},axis=1)

/home/arsalanado/Documents/projects/github/mystash/denorm_env/lib/python3.9/site-packages/pandas/core/frame.py:9190: FutureWarning: Passing 'suffixes' which cause duplicate columns {'UpdatedAt_x', 'CreatedAt_x'} in the result is deprecated and will raise a MergeError in a future version.
  return merge(

In [42]:
worker_scan_table_denorm = worker_scan_table.merge(line_table, how='left', on='LineID').merge(machine_table_denorm, how='left',on='MachineID').merge(worker_table, how='left',left_on='ActiveWorkerID', right_on='WorkerID')

In [43]:
worker_scan_table_denorm.drop(['HasExpired', 'EndedAt','CreatedAt_x', 'UpdatedAt_x','WorkerID','WorkerID_y','LineID_y','LineCode_y','LineDescription_y','WorkerCode_y', 'WorkerDescription_y', 'WorkerImageUrl_y','WorkerThumbnailUrl_y', 'AllocatedMachines_y','CreatedAt_y', 'UpdatedAt_y','CreatedAt_y', 'UpdatedAt_y'], axis=1, inplace=True)

In [44]:
worker_scan_table_denorm = worker_scan_table_denorm.rename({'WorkerCode_x':'WorkerCode','LineCode_x':'LineCode', 'WorkerDescription_x':'WorkerDescription','WorkerImageUrl_x':'WorkerImageUrl', 'WorkerThumbnailUrl_x':'WorkerThumbnailUrl', 'AllocatedMachines_x':'AllocatedMachines','WorkerID_x':'WorkerID', 'LineID_x':'LineID','LineDescription_x':'LineDescription','CreatedAt_x':'CreatedAt', 'UpdatedAt_x':'UpdatedAt'},axis=1)

In [45]:
worker_scan_table_denorm.columns

Index(['WorkerScanID', 'WorkerID', 'LineID', 'MachineID', 'WorkerOperations',
       'LineCode', 'LineDescription', 'MachineCode', 'MachineDescription',
       'MachineImageUrl', 'MachineThumbnailUrl', 'MachineTypeID',
       'ActiveWorkerID', 'Operations', 'BoxID', 'MachineTypeCode',
       'MachineTypeDescription', 'Allowance', 'WorkerCode',
       'WorkerDescription', 'WorkerImageUrl', 'WorkerThumbnailUrl',
       'AllocatedMachines', 'CreatedAt', 'UpdatedAt'],
      dtype='object')

In [46]:
operation_table_denorm = operation_table.merge(section_table, how='left',on='SectionID')
operation_table_denorm.drop(['CreatedAt_y','UpdatedAt_y'], axis=1, inplace=True)
operation_table_denorm = operation_table_denorm.rename({'CreatedAt_x':'CreatedAt', 'UpdatedAt_x':'UpdatedAt'},axis=1)

In [47]:
production_order_table_denorm = production_order_table.merge(sale_order_table, how='left',on='SaleOrderID').merge(style_template_table, how='left',on='StyleTemplateID')
production_order_table_denorm = production_order_table_denorm.drop(["CreatedAt_x", "UpdatedAt_x", "CreatedAt_y", "UpdatedAt_y"], axis=1)

In [48]:
marker_table_denorm = marker_table.merge(production_order_table_denorm, how='left',on='ProductionOrderID')
marker_table_denorm = marker_table_denorm.drop(["CreatedAt_x", "UpdatedAt_x", "CreatedAt_y", "UpdatedAt_y"], axis=1)

In [49]:
cut_job_table_denorm = cut_job_table.merge(production_order_table_denorm, how='left', on='ProductionOrderID').merge(marker_table_denorm, how='left', on='MarkerID')

cut_job_table_denorm.drop(['CreatedAt_y','UpdatedAt_y','ProductionOrderID_y','ProductionOrderCode_y', 'SaleOrderID_y', 'StyleTemplateID_y',
       'FollowsOperationSequence_y', 'SaleOrderCode_y', 'Customer_y','OrderQuantity_y','StyleTemplateCode_y'], axis=1, inplace=True)

cut_job_table_denorm =  cut_job_table_denorm.rename({'ProductionOrderID_x':'ProductionOrderID',
       'CreatedAt_x':'CreatedAt', 'UpdatedAt_x':'UpdatedAt', 'ProductionOrderCode_x':'ProductionOrderCode', 'SaleOrderID_x':'SaleOrderID',
       'StyleTemplateID_x':'StyleTemplateID', 'FollowsOperationSequence_x':'FollowsOperationSequence', 'SaleOrderCode_x':'SaleOrderCode',
       'Customer_x':'Customer', 'OrderQuantity_x':'OrderQuantity', 'StyleTemplateCode_x':'StyleTemplateCode'}, axis=1)

In [50]:
cut_report_table_denorm = cut_report_table.merge(cut_job_table_denorm, how='left', on='CutJobID')
cut_report_table_denorm.drop(['CreatedAt_y','UpdatedAt_y'], axis=1, inplace=True)
cut_report_table_denorm = cut_report_table_denorm.rename({'CreatedAt_x':'CreatedAt', 'UpdatedAt_x':'UpdatedAt'},axis=1)

In [51]:
piece_wise_cut_report_table_denorm = piece_wise_cut_report_table.merge(cut_report_table_denorm, how='left',on='BundleID')
piece_wise_cut_report_table_denorm = piece_wise_cut_report_table_denorm.drop(["CreatedAt_y", "UpdatedAt_y"], axis=1)
piece_wise_cut_report_table_denorm = piece_wise_cut_report_table_denorm.rename({'CreatedAt_x':'CreatedAt', 'UpdatedAt_x':'UpdatedAt'},axis=1)

In [52]:
scan_table_denorm = scan_table.merge(worker_scan_table_denorm, how='left',on='WorkerScanID').merge(operation_table_denorm, how='left',on='OperationID').merge(piece_wise_cut_report_table_denorm, how='left',on='PieceID')

scan_table_denorm = scan_table_denorm.drop(['BundleID_y','WorkerID_y','WorkerID_y', 'LineID_y','MachineID_y','CreatedAt_x', 'UpdatedAt_x','CreatedAt_y','UpdatedAt_y'], axis=1)
scan_table_denorm = scan_table_denorm.rename({'BundleID_x':'BundleID','CreatedAt_x':'CreatedAt', 'UpdatedAt_x':'UpdatedAt','WorkerID_x':'WorkerID', 'LineID_x':'LineID', 'MachineID_x':'MachineID'},axis=1)

/home/arsalanado/Documents/projects/github/mystash/denorm_env/lib/python3.9/site-packages/pandas/core/frame.py:9190: FutureWarning: Passing 'suffixes' which cause duplicate columns {'UpdatedAt_x', 'CreatedAt_x'} in the result is deprecated and will raise a MergeError in a future version.
  return merge(

In [53]:
piece_wise_scan_table_denorm = piece_wise_scan_table.merge(scan_table_denorm, how='left', on='ScanID')

piece_wise_scan_table_denorm = piece_wise_scan_table_denorm.drop(['BundleID_y', 'PieceID_y', 'OperationID_y', 'WorkerID_y', 'LineID_y', 'MachineID_y','BundleID_y','WorkerID_y','WorkerID_y', 'LineID_y','MachineID_y',], axis=1)
piece_wise_scan_table_denorm = piece_wise_scan_table_denorm.rename({'BundleID_x':'BundleID', 'PieceID_x':'PieceID', 'OperationID_x':'OperationID',
       'WorkerID_x':'WorkerID', 'LineID_x':'LineID', 'MachineID_x':'MachineID', 'CreatedAt_x':'CreatedAt', 'UpdatedAt_x':'UpdatedAt'},axis=1)

In [54]:
style_bulletin_table_denorm = style_bulletin_table.merge(machine_type_table, how='left', on='MachineTypeID').merge(operation_table_denorm, how='left', on='OperationID').merge(style_template_table, how='left', on='StyleTemplateID')

style_bulletin_table_denorm.drop(['CreatedAt_x','UpdatedAt_x','CreatedAt_y','UpdatedAt_y'], axis=1, inplace=True)

In [55]:
tag_table_denorm =  tag_table.merge(cut_report_table_denorm, how='left', on='BundleID')
tag_table_denorm.drop(['CreatedAt_y','UpdatedAt_y'], axis=1, inplace=True)
tag_table_denorm = tag_table_denorm.rename({'CreatedAt_x':'CreatedAt', 'UpdatedAt_x':'UpdatedAt'},axis=1)

In [56]:
user_table_denorm = user_table.merge(line_table, how='left',on='LineID').merge(section_table, how='left', on='SectionID')
user_table_denorm = user_table_denorm.drop(["CreatedAt_x", "UpdatedAt_x", "CreatedAt_y", "UpdatedAt_y"], axis=1)

In [57]:
userpermission_table_denorm = userpermission_table.merge(module_table, how='left', on='ModuleID').merge(user_table_denorm, how='left', on='UserID')
userpermission_table_denorm = userpermission_table_denorm.drop(["CreatedAt_x", "UpdatedAt_x", "CreatedAt_y", "UpdatedAt_y"], axis=1)

In [127]:
connection = engine_postgres.raw_connection()

import time
import os
import psycopg2
import numpy as np
import psycopg2.extras as extras
from io import StringIO
def copy_from_file(conn, df, table):
    """
    Here we are going save the dataframe on disk as 
    a csv file, load the csv file  
    and use copy_from() to copy it to the table
    """
    # Save the dataframe to disk
    tmp_df = "./tmp_dataframe.csv"
    df.iloc[:,1:].to_csv(tmp_df, index_label='id', header=False)
    f = open(tmp_df, 'r')
    cursor = conn.cursor()
    try:
        cursor.copy_from(f, table, sep=",")
        conn.commit()
    except (Exception, psycopg2.DatabaseError) as error:
        os.remove(tmp_df)
        print("Error: %s" % error)
        conn.rollback()
        cursor.close()
        return 1
    print("copy_from_file() done")
    cursor.close()
    # os.remove(tmp_df)

In [125]:
user_table_denorm

,UserID,UserName,Password,UserType,LineID,SectionID,LineCode,LineDescription,SectionCode,SectionDescription,CreatedAt,UpdatedAt
0,1,test,test,Administrator,1,1,Line-1,Line-1,Section-1,Section-1,2022-01-12 17:20:29,2022-01-12 17:20:29
1,2,test1,test1,Supervisor,7,7,test2,test2,test2,test2,2022-01-14 07:50:54,2022-01-14 07:50:54
2,3,worker,worker,Worker,7,7,test2,test2,test2,test2,2022-01-14 07:50:54,2022-01-14 07:50:54
3,4,supervisor,supervisor,Supervisor,7,7,test2,test2,test2,test2,2022-01-14 07:50:54,2022-01-14 07:50:54
4,5,administrator,administrator,Administrator,7,7,test2,test2,test2,test2,2022-01-14 07:50:54,2022-01-14 07:50:54

In [128]:
user_table_denorm.dtypes

UserID                         Int64
UserName                      string
Password                      string
UserType                      string
LineID                         Int64
SectionID                      Int64
LineCode                      string
LineDescription               string
SectionCode                   string
SectionDescription            string
CreatedAt             datetime64[ns]
UpdatedAt             datetime64[ns]
dtype: object

In [126]:
copy_from_file(connection,user_table_denorm,'user')

Error: invalid input syntax for type integer: "Line-1"
CONTEXT:  COPY user, line 1, column SectionID: "Line-1"

1

In [87]:
line_table.set_index("LineID",inplace=True,drop=True)
line_table.head(3)

       LineCode LineDescription           CreatedAt           UpdatedAt
LineID
1        Line-1          Line-1 2022-01-12 17:20:55 2022-01-12 17:20:55
2        Line-2          Line-2 2022-01-12 17:20:55 2022-01-12 17:20:55
3        Line-3          Line-3 2022-01-12 17:20:55 2022-01-12 17:20:55

In [106]:
df=user_table_denorm
conn=connection
table='user'

tmp_df = "./tmp_dataframe.csv"
df.to_csv(tmp_df, index_label='id', header=False)
f = open(tmp_df, 'r')
cursor = conn.cursor()
try:
    cursor.copy_from(f, table, sep=",")
    conn.commit()
except (Exception, psycopg2.DatabaseError) as error:
    os.remove(tmp_df)
    print("Error: %s" % error)
    conn.rollback()
    cursor.close()

Error: extra data after last expected column
CONTEXT:  COPY user, line 1: "0,1,test,test,Administrator,1,1,Line-1,Line-1,Section-1,Section-1,2022-01-12 17:20:29,2022-01-12 17:..."

In [100]:
user_table_denorm

,UserID,UserName,Password,UserType,LineID,SectionID,LineCode,LineDescription,SectionCode,SectionDescription,CreatedAt,UpdatedAt
0,1,test,test,Administrator,1,1,Line-1,Line-1,Section-1,Section-1,2022-01-12 17:20:29,2022-01-12 17:20:29
1,2,test1,test1,Supervisor,7,7,test2,test2,test2,test2,2022-01-14 07:50:54,2022-01-14 07:50:54
2,3,worker,worker,Worker,7,7,test2,test2,test2,test2,2022-01-14 07:50:54,2022-01-14 07:50:54
3,4,supervisor,supervisor,Supervisor,7,7,test2,test2,test2,test2,2022-01-14 07:50:54,2022-01-14 07:50:54
4,5,administrator,administrator,Administrator,7,7,test2,test2,test2,test2,2022-01-14 07:50:54,2022-01-14 07:50:54

In [107]:
df=user_table_denorm

tmp_df = "./tmp_dataframe.csv"
df.to_csv(tmp_df, index=False, header=False)

f = open(tmp_df, 'r')

## Successfully Inserted tables

In [37]:
if line_table.columns[0]=='LineID':
    line_table.set_index(['LineID'], inplace = True, drop = True)

upsert(con=engine_postgres,
       df=line_table,
       table_name='line',
       if_row_exists='ignore',
       dtype=None,
       create_table=False)

In [ ]:
# line_table.to_sql(
#     'line', 
#     con=engine_postgres, 
#     index=False, 
#     if_exists='append'
# )
# print("to_sql() done (sqlalchemy)")

In [27]:
if module_table.columns[0]=='ModuleID':
    module_table.set_index(['ModuleID'], inplace = True, drop = True)

upsert(con=engine_postgres,
       df=module_table,
       table_name='module',
       if_row_exists='ignore',
       dtype=None,
       create_table=False)

In [28]:
if userpermission_table_denorm.columns[0]=='UserPermissionID':
    userpermission_table_denorm.set_index(['UserPermissionID'], inplace = True, drop = True)

upsert(con=engine_postgres,
       df=userpermission_table_denorm,
       table_name='userpermission',
       if_row_exists='ignore',
       dtype=None,
       create_table=False)

In [29]:
if worker_table.columns[0]=='WorkerID':
    worker_table.set_index(['WorkerID'], inplace = True, drop = True)

upsert(con=engine_postgres,
       df=worker_table,
       table_name='worker',
       if_row_exists='ignore',
       dtype=None,
       create_table=False)

In [30]:
if machine_table_denorm.columns[0]=='MachineID':
    machine_table_denorm.set_index(['MachineID'], inplace = True, drop = True)

upsert(con=engine_postgres,
       df=machine_table_denorm,
       table_name='machine',
       if_row_exists='ignore',
       dtype=None,
       create_table=False)

In [31]:
if sale_order_table.columns[0]=='SaleOrderID':
    sale_order_table.set_index(['SaleOrderID'], inplace = True, drop = True)

upsert(con=engine_postgres,
       df=sale_order_table,
       table_name='sale_order',
       if_row_exists='ignore',
       dtype=None,
       create_table=False)

In [32]:
if section_table.columns[0]=='SectionID':
    section_table.set_index(['SectionID'], inplace = True, drop = True)

upsert(con=engine_postgres,
       df=section_table,
       table_name='section',
       if_row_exists='ignore',
       dtype=None,
       create_table=False)

In [33]:
if user_table_denorm.columns[0]=='UserID':
    user_table_denorm.set_index(['UserID'], inplace = True, drop = True)

upsert(con=engine_postgres,
       df=user_table_denorm,
       table_name='user',
       if_row_exists='ignore',
       dtype=None,
       create_table=False)

In [34]:
if operation_table_denorm.columns[0]=='OperationID':
    operation_table_denorm.set_index(['OperationID'], inplace = True, drop = True)

upsert(con=engine_postgres,
       df=operation_table_denorm,
       table_name='operation',
       if_row_exists='ignore',
       dtype=None,
       create_table=False)

In [35]:
if machine_type_table.columns[0]=='MachineTypeID':
    machine_type_table.set_index(['MachineTypeID'], inplace = True, drop = True)

upsert(con=engine_postgres,
       df=machine_type_table,
       table_name='machine_type',
       if_row_exists='ignore',
       dtype=None,
       create_table=False)

In [36]:
if machine_table_denorm.columns[0]=='MachineID':
    machine_table_denorm.set_index(['MachineID'], inplace = True, drop = True)

upsert(con=engine_postgres,
       df=machine_table_denorm,
       table_name='machine',
       if_row_exists='ignore',
       dtype=None,
       create_table=False)

In [38]:
if worker_scan_table_denorm.columns[0]=='WorkerScanID':
    worker_scan_table_denorm.set_index(['WorkerScanID'], inplace = True, drop = True)
    
upsert(con=engine_postgres,
       df=worker_scan_table_denorm.iloc[:1,:],
       table_name='worker_scan',
       if_row_exists='ignore',
       dtype=None,
       chunksize=1,
       create_table=False)

In [78]:
if style_template_table.columns[0]=='StyleTemplateID':
    style_template_table.set_index(['StyleTemplateID'], inplace = True, drop = True)

upsert(con=engine_postgres,
       df=style_template_table,
       table_name='style_template',
       if_row_exists='ignore',
       dtype=None,
       create_table=False)

In [79]:
if style_bulletin_table_denorm.columns[0]=='StyleBulletinID':
    style_bulletin_table_denorm.set_index(['StyleBulletinID'], inplace = True, drop = True)

upsert(con=engine_postgres,
       df=style_bulletin_table_denorm,
       table_name='style_bulletin',
       if_row_exists='ignore',
       dtype=None,
       create_table=False)

In [80]:
if production_order_table_denorm.columns[0]=='ProductionOrderID':
    production_order_table_denorm.set_index(['ProductionOrderID'], inplace = True, drop = True)

upsert(engine=engine_postgres,
       df=production_order_table_denorm,
       table_name='production_order',
       if_row_exists='ignore',
       dtype=None,
       create_table=False)

In [81]:
if marker_table_denorm.columns[0]=='MarkerID':
    marker_table_denorm.set_index(['MarkerID'], inplace = True, drop = True)

upsert(con=engine_postgres,
       df=marker_table_denorm,
       table_name='marker',
       if_row_exists='ignore',
       dtype=None,
       create_table=False)

In [82]:
if cut_job_table_denorm.columns[0]=='CutJobID':
    cut_job_table_denorm.set_index(['CutJobID'], inplace = True, drop = True)

upsert(con=engine_postgres,
       df=cut_job_table_denorm,
       table_name='cut_job',
       if_row_exists='ignore',
       dtype=None,
       create_table=False)

In [83]:
if cut_report_table_denorm.columns[0]=='BundleID':
    cut_report_table_denorm.set_index(['BundleID'], inplace = True, drop = True)

upsert(con=engine_postgres,
       df=cut_report_table_denorm,
       table_name='cut_report',
       if_row_exists='ignore',
       dtype=None,
       create_table=False)

In [84]:
if tag_table_denorm.columns[0]=='TagID':
    tag_table_denorm.set_index(['TagID'], inplace = True, drop = True)

upsert(con=engine_postgres,
       df=tag_table_denorm,
       table_name='tag',
       if_row_exists='ignore',
       dtype=None,
       create_table=False)

In [85]:
if scan_table_denorm.columns[0]=='ScanID':
    scan_table_denorm.set_index(['ScanID'], inplace = True, drop = True)

upsert(con=engine_postgres,
       df=scan_table_denorm,
       table_name='scan',
       if_row_exists='ignore',
       dtype=None,
       create_table=False)

In [86]:
if piece_wise_scan_table_denorm.columns[0]=='PieceWiseScanningID':
    piece_wise_scan_table_denorm.set_index(['PieceWiseScanningID'], inplace = True, drop = True)

upsert(con=engine_postgres,
       df=piece_wise_scan_table_denorm,
       table_name='piece_wise_scan',
       if_row_exists='ignore',
       dtype=None,
       create_table=False)

In [87]:
if piece_wise_cut_report_table_denorm.columns[0]=='PieceID':
    piece_wise_cut_report_table_denorm.set_index(['PieceID'], inplace = True, drop = True)

upsert(con=engine_postgres,
       df=piece_wise_cut_report_table_denorm,
       table_name='piece_wise_cut_report',
       if_row_exists='ignore',
       dtype=None,
       create_table=False)

## Creating Models

### worker table

In [33]:
Base = declarative_base()

class Machine(Base):
    __tablename__ = 'machine'
    
    MachineID  = Column(Integer, primary_key=True,  autoincrement=False)

    MachineCode = Column(String(64))
    MachineDescription = Column( String(64))
    MachineImageUrl = Column( String(2056))
    MachineThumbnailUrl = Column( String(2056))
    MachineTypeID = Column( Integer,ForeignKey("machine_type.MachineTypeID"))
    ActiveWorkerID =Column( Integer, ForeignKey("worker.WorkerID"))
    LineID = Column( Integer,ForeignKey("line.LineID"))
    Operations =Column( JSON)

    LineCode =Column( String(64))
    LineDescription =Column( String(64))  

    MachineTypeCode =Column(String(64))
    MachineTypeDescription=Column( String(64))
    Allowance=Column( Float)    

    WorkerID=Column(Integer)

    WorkerCode=Column(String(64))
    WorkerDescription=Column( String(64))
    WorkerImageUrl=Column(String(2056))
    WorkerThumbnailUrl=Column(String(2056))
    AllocatedMachines=Column(JSON)
    CreatedAt=Column(DateTime)
    UpdatedAt =Column(DateTime)
    BoxID=Column(Integer)

    line = relationship("Line")
    machine_type = relationship("MachineType")
    worker = relationship("Worker")
    
class Line(Base):
    __tablename__ = 'line'
    
    LineID=Column(Integer, primary_key = True, autoincrement=False)

    LineCode=Column(String(64))
    LineDescription=Column(String(64))
    CreatedAt=Column(DateTime)
    UpdatedAt=Column(DateTime)

class MachineType(Base):
    __tablename__ = 'machine_type'

    MachineTypeID=Column(Integer, primary_key = True, autoincrement=False)

    MachineTypeCode=Column(String(64))
    MachineTypeDescription=Column(String(64))
    Allowance=Column(Float)
    CreatedAt=Column(DateTime)
    UpdatedAt=Column(DateTime)

class Worker(Base):
    __tablename__ = 'worker'

    WorkerID=Column(Integer, primary_key = True, autoincrement=False)

    WorkerCode=Column(String(64))
    WorkerDescription=Column(String(64))
    WorkerImageUrl=Column(String(2056))
    WorkerThumbnailUrl=Column(String(2056))
    AllocatedMachines=Column(JSON)
    CreatedAt=Column( DateTime)
    UpdatedAt=Column(DateTime)

In [34]:
class WorkerScan(Base):
    __tablename__ = 'worker_scan'
    __table_args__ = {'extend_existing': True} #additional arguments to be supplied to the Table constructor should be provided using the __table_args__ declarative class attribute.

    WorkerScanID=Column(BIGINT, primary_key = True, autoincrement=False) 

    WorkerID =Column(Integer, ForeignKey("worker.WorkerID"))
    LineID=Column(Integer,ForeignKey("line.LineID"))
    MachineID=Column(Integer,ForeignKey("machine.MachineID"))
    WorkerOperations=Column(JSON)

    HasExpired=Column(Integer)
    EndedAt=Column(DateTime) 

    WorkerCode=Column(String(64))
    WorkerDescription=Column(String(64)) 
    WorkerImageUrl=Column(String(2056)) 
    WorkerThumbnailUrl=Column(String(2056)) 
    AllocatedMachines=Column(JSON)

    LineCode=Column(String(64))
    LineDescription=Column(String(64)) 

    MachineCode=Column(String(64))
    MachineDescription=Column(String(64))
    MachineImageUrl=Column(String(2056)) 
    MachineThumbnailUrl=Column(String(2056))

    MachineTypeID=Column(Integer, ForeignKey("machine_type.MachineTypeID"))
    ActiveWorkerID=Column(Integer)
    Operations=Column(JSON)
    MachineTypeCode=Column(String(64)) 
    MachineTypeDescription=Column(String(64)) 
    Allowance=Column(Float)

    CreatedAt=Column(DateTime) 
    UpdatedAt=Column(DateTime)  

    line = relationship("Line")
    machine = relationship("Machine")
    worker = relationship("Worker")
    machine_type = relationship("MachineType")

In [35]:
class ProductionOrder(Base):
    __tablename__ = 'production_order'
    __table_args__ = {'extend_existing': True}

    ProductionOrderID=Column(Integer, primary_key = True, autoincrement=False) 
    
    ProductionOrderCode=Column(String(64))
    SaleOrderID=Column(Integer, ForeignKey("sale_order.SaleOrderID"))
    StyleTemplateID=Column(Integer, ForeignKey("style_template.StyleTemplateID"))    
    IsFollowOperationSequence=Column(Boolean)
    
    SaleOrderCode=Column(String(100))
    Customer=Column(String(64))
    OrderQuantity=Column(Integer)            

    StyleTemplateCode=Column(String(64))

    CreatedAt=Column(DateTime) 
    UpdatedAt=Column(DateTime)  
    
    sale_order = relationship("SaleOrder")
    style_template = relationship("StyleTemplate")

class SaleOrder(Base):
    __tablename__ = 'sale_order'
    __table_args__ = {'extend_existing': True}

    SaleOrderID=Column(Integer, primary_key = True, autoincrement=False) 
    SaleOrderCode=Column(String(100))

    Customer=Column(String(64))
    OrderQuantity=Column(Integer)     
    CreatedAt=Column(DateTime) 
    UpdatedAt=Column(DateTime)  

class StyleTemplate(Base):
    __tablename__ = 'style_template'
    __table_args__ = {'extend_existing': True}

    StyleTemplateID=Column(Integer, primary_key = True, autoincrement=False) 
    StyleTemplateCode=Column(String(64))     
    CreatedAt=Column(DateTime) 
    UpdatedAt=Column(DateTime)

In [36]:
class Marker(Base):
    __tablename__ = 'marker'
    __table_args__ = {'extend_existing': True}

    MarkerID=Column(Integer, primary_key = True, autoincrement=False) 
    MarkerCode=Column(String(64))    
    ProductionOrderID=Column(Integer, ForeignKey("production_order.ProductionOrderID"))
    ProductionOrderCode=Column(String(64))
    
    SaleOrderID=Column(Integer, ForeignKey("sale_order.SaleOrderID"))
    SaleOrderCode=Column(String(100))
    Customer=Column(String(64))
    OrderQuantity=Column(Integer)    
    
    StyleTemplateID=Column(Integer, ForeignKey("style_template.StyleTemplateID"))
    StyleTemplateCode=Column(String(64))   
    FollowsOperationSequence=Column(Boolean)
    
    MarkerMapping=Column(JSON)  
    Size=Column(Integer) 
    Inseam=Column(Integer) 
    Ratio=Column(Integer) 

    UpdatedAt=Column(DateTime)  
    CreatedAt=Column(DateTime) 

    production_order = relationship("ProductionOrder")
    sale_order = relationship("SaleOrder")
    style_template = relationship("StyleTemplate")

In [37]:
class CutJob(Base):
    __tablename__ = 'cut_job'
    __table_args__ = {'extend_existing': True}

    CutJobID=Column(Integer, primary_key = True, autoincrement=False) 
    CutNo=Column(Integer)
    CutQuantity=Column(Integer)

    MarkerID=Column(Integer, ForeignKey("marker.MarkerID")) 
    MarkerCode=Column(String(64))    
    ProductionOrderID=Column(Integer, ForeignKey("production_order.ProductionOrderID"))
    ProductionOrderCode=Column(String(64))
    
    SaleOrderID=Column(Integer, ForeignKey("sale_order.SaleOrderID"))
    SaleOrderCode=Column(String(100))
    Customer=Column(String(64))
    OrderQuantity=Column(Integer)    
    
    StyleTemplateID=Column(Integer, ForeignKey("style_template.StyleTemplateID"))
    StyleTemplateCode=Column(String(64))   
    FollowsOperationSequence=Column(Boolean)
    
    MarkerMapping=Column(JSON)    
    UpdatedAt=Column(DateTime)  
    CreatedAt=Column(DateTime) 

    production_order = relationship("ProductionOrder")
    sale_order = relationship("SaleOrder")
    style_template = relationship("StyleTemplate")
    marker = relationship("Marker")

In [38]:
class CutReport(Base):
    __tablename__ = 'cut_report'
    __table_args__ = {'extend_existing': True}

    BundleID=Column(Integer, primary_key = True, autoincrement=False)
    
    BundleCode=Column(String(64))
    BundleQuantity=Column(Integer)
    ScannedQuantity=Column(Integer)
    RemainingQuantity=Column(Integer)
    CutJobID=Column(Integer, ForeignKey("cut_job.CutJobID"))
    CutNo=Column(Integer)
    CutQuantity=Column(Integer)
    MarkerID=Column(Integer, ForeignKey("marker.MarkerID")) 
    MarkerCode=Column(String(64))    
    ProductionOrderID=Column(Integer, ForeignKey("production_order.ProductionOrderID"))
    ProductionOrderCode=Column(String(64))
    
    SaleOrderID=Column(Integer, ForeignKey("sale_order.SaleOrderID"))
    SaleOrderCode=Column(String(100))
    Customer=Column(String(64))
    OrderQuantity=Column(Integer)    
    
    StyleTemplateID=Column(Integer, ForeignKey("style_template.StyleTemplateID"))
    StyleTemplateCode=Column(String(64))   
    FollowsOperationSequence=Column(Boolean)
    
    MarkerMapping=Column(JSON)    
    UpdatedAt=Column(DateTime)  
    CreatedAt=Column(DateTime) 

    cut_job = relationship("CutJob")
    production_order = relationship("ProductionOrder")
    sale_order = relationship("SaleOrder")
    style_template = relationship("StyleTemplate")
    marker = relationship("Marker")

In [39]:
class Operation(Base):
    __tablename__ = 'operation'
    __table_args__ = {'extend_existing': True}

    OperationID=Column(Integer, primary_key = True, autoincrement=False) 
    OperationCode=Column(String(64))    
    OperationName =Column(String(64))
    OperationDescription = Column(String(64))    
    Department = Column(String(64))
    PieceRate=Column(Integer)      

    OperationType=Column(String(64))
    OperationImageUrl=Column(String(2056))
    OperationThumbnailUrl=Column(String(2056))

    SectionID = Column(Integer, ForeignKey("section.SectionID"))
    SectionCode=Column(String(64))
    SectionDescription=Column(String(64))    

    CreatedAt=Column(DateTime) 
    UpdatedAt=Column(DateTime)  

    section = relationship("Section")

class Section(Base):
    __tablename__ = 'section'
    __table_args__ = {'extend_existing': True}

    SectionID=Column(Integer, primary_key = True, autoincrement=False) 
    SectionCode=Column(String(64))
    SectionDescription=Column(String(64))
    CreatedAt=Column(DateTime) 
    UpdatedAt=Column(DateTime)

In [40]:
class PieceWiseCutReport(Base):
    __tablename__ = 'piece_wise_cut_report'
    __table_args__ = {'extend_existing': True}

    PieceID=Column(Integer, primary_key = True, autoincrement=False)
    BundleID=Column(Integer, ForeignKey("cut_report.BundleID"))
    PieceNumber=Column(Integer)

    BundleCode=Column(String(64)) 
    BundleQuantity=Column(Integer)
    ScannedQuantity=Column(Integer)
    RemainingQuantity=Column(Integer)
    CutJobID=Column(Integer, ForeignKey("cut_job.CutJobID"))
    CutNo=Column(Integer) 
    CutQuantity=Column(Integer)

    MarkerID=Column(Integer, ForeignKey("marker.MarkerID")) 
    MarkerCode=Column(String(64))    
    ProductionOrderID=Column(Integer, ForeignKey("production_order.ProductionOrderID"))
    ProductionOrderCode=Column(String(64))
    
    SaleOrderID=Column(Integer, ForeignKey("sale_order.SaleOrderID"))
    SaleOrderCode=Column(String(100))
    Customer=Column(String(64))
    OrderQuantity=Column(Integer)    
    
    StyleTemplateID=Column(Integer, ForeignKey("style_template.StyleTemplateID"))
    StyleTemplateCode=Column(String(64))   
    FollowsOperationSequence=Column(Boolean)
    
    MarkerMapping=Column(JSON)    
    UpdatedAt=Column(DateTime)  
    CreatedAt=Column(DateTime) 

    production_order = relationship("ProductionOrder")
    sale_order = relationship("SaleOrder")
    style_template = relationship("StyleTemplate")
    marker = relationship("Marker")
    cut_report = relationship("CutReport")
    cut_job = relationship("CutJob")

In [41]:
class Scan(Base):
    __tablename__ = 'scan'
    __table_args__ = {'extend_existing': True}

    ScanID=Column(BIGINT, primary_key = True, autoincrement=False)
    WorkerScanID=Column(BIGINT, ForeignKey("worker_scan.WorkerScanID")) 

    WorkerID =Column(Integer, ForeignKey("worker.WorkerID"))
    LineID=Column(Integer,ForeignKey("line.LineID"))
    MachineID=Column(Integer,ForeignKey("machine.MachineID"))
    WorkerOperations=Column(JSON)

    WorkerCode=Column(String(64))
    WorkerDescription=Column(String(64)) 
    WorkerImageUrl=Column(String(2056)) 
    WorkerThumbnailUrl=Column(String(2056)) 
    AllocatedMachines=Column(JSON)

    LineCode=Column(String(64))
    LineDescription=Column(String(64)) 

    MachineCode=Column(String(64))
    MachineDescription=Column(String(64))
    MachineImageUrl=Column(String(2056)) 
    MachineThumbnailUrl=Column(String(2056))

    MachineTypeID=Column(Integer)
    ActiveWorkerID=Column(Integer)
    Operations=Column(JSON)
    MachineTypeCode=Column(String(64)) 
    MachineTypeDescription=Column(String(64)) 
    Allowance=Column(Float)

    ShortAddress=Column(String(64)) 
    LongAddress=Column(String(64)) 
    HostIP=Column(String(64)) 

    PieceID=Column(Integer)
    BundleID=Column(Integer, ForeignKey("cut_report.BundleID"))
    PieceNumber=Column(Integer)

    BundleCode=Column(String(64)) 
    BundleQuantity=Column(Integer)
    ScannedQuantity=Column(Integer)
    RemainingQuantity=Column(Integer)
    CutJobID=Column(Integer, ForeignKey("cut_job.CutJobID"))
    CutNo=Column(Integer) 

    CutQuantity=Column(Integer)


    MarkerID=Column(Integer, ForeignKey("marker.MarkerID")) 
    MarkerCode=Column(String(64))    
    ProductionOrderID=Column(Integer, ForeignKey("production_order.ProductionOrderID"))
    ProductionOrderCode=Column(String(64))
    
    SaleOrderID=Column(Integer, ForeignKey("sale_order.SaleOrderID"))
    SaleOrderCode=Column(String(100))
    Customer=Column(String(64))
    OrderQuantity=Column(Integer)    
    
    StyleTemplateID=Column(Integer, ForeignKey("style_template.StyleTemplateID"))
    StyleTemplateCode=Column(String(64))   
    FollowsOperationSequence=Column(Boolean)
    
    MarkerMapping=Column(JSON)    
    UpdatedAt=Column(DateTime)  
    CreatedAt=Column(DateTime) 

    # newly added columns

    OperationID=Column(Integer,ForeignKey("operation.OperationID"))
    OperationCode=Column(String(64))
    OperationName=Column(String(64))
    OperationDescription=Column(String(64))
    Department=Column(String(64))
    PieceRate=Column(Integer)
    OperationType=Column(String(64))
    OperationImageUrl=Column(String(2056))
    OperationThumbnailUrl=Column(String(2056))
    
    SectionID=Column(Integer, ForeignKey("section.SectionID"))
    SectionCode=Column(String(64))
    SectionDescription=Column(String(64))


    section = relationship("Section")
    operation = relationship("Operation")

    production_order = relationship("ProductionOrder")
    sale_order = relationship("SaleOrder")
    style_template = relationship("StyleTemplate")
    marker = relationship("Marker")
    cut_report = relationship("CutReport")
    cut_job = relationship("Cutjob")
    machine = relationship("Machine")
    line = relationship("Line")
    worker = relationship("Worker")    
    worker_scan = relationship("WorkerScan")

In [42]:
class PieceWiseScan(Base):
    __tablename__ = 'piece_wise_scan'
    __table_args__ = {'extend_existing': True}

    PieceWiseScanningID=Column(Integer, primary_key = True, autoincrement=False)

    ScanID=Column(BIGINT, ForeignKey("scan.ScanID"))
    WorkerScanID=Column(BIGINT, ForeignKey("worker_scan.WorkerScanID")) 

    WorkerID =Column(Integer, ForeignKey("worker.WorkerID"))
    LineID=Column(Integer,ForeignKey("line.LineID"))
    MachineID=Column(Integer,ForeignKey("machine.MachineID"))
    WorkerOperations=Column(JSON)

    WorkerCode=Column(String(64))
    WorkerDescription=Column(String(64)) 
    WorkerImageUrl=Column(String(2056)) 
    WorkerThumbnailUrl=Column(String(2056)) 
    AllocatedMachines=Column(JSON)

    LineCode=Column(String(64))
    LineDescription=Column(String(64)) 

    MachineCode=Column(String(64))
    MachineDescription=Column(String(64))
    MachineImageUrl=Column(String(2056)) 
    MachineThumbnailUrl=Column(String(2056))

    MachineTypeID=Column(Integer)
    ActiveWorkerID=Column(Integer)
    Operations=Column(JSON)
    MachineTypeCode=Column(String(64)) 
    MachineTypeDescription=Column(String(64)) 
    Allowance=Column(Float)

    PieceID=Column(Integer, ForeignKey("piece_wise_cut_report.PieceID"))
    BundleID=Column(Integer, ForeignKey("cut_report.BundleID"))
    PieceNumber=Column(Integer)

    OperationID=Column(Integer, ForeignKey("operation.OperationID")) 
    OperationCode=Column(String(64))    
    OperationName =Column(String(64))
    OperationDescription = Column(String(64))      
    Department = Column(String(64))
    PieceRate=Column(Integer)      
    OperationType=Column(String(64))
    OperationImageUrl=Column(String(2056))
    OperationThumbnailUrl=Column(String(2056))

    SectionID = Column(Integer, ForeignKey("section.SectionID"))
    SectionCode=Column(String(64))
    SectionDescription=Column(String(64))    

    BundleCode=Column(String(64)) 
    BundleQuantity=Column(Integer)
    ScannedQuantity=Column(Integer)
    RemainingQuantity=Column(Integer)
    CutJobID=Column(Integer, ForeignKey("cut_job.CutJobID"))
    CutNo=Column(Integer)
    CutQuantity=Column(Integer)

    MarkerID=Column(Integer, ForeignKey("marker.MarkerID")) 
    MarkerCode=Column(String(64))    
    ProductionOrderID=Column(Integer, ForeignKey("production_order.ProductionOrderID"))
    ProductionOrderCode=Column(String(64))
    
    SaleOrderID=Column(Integer, ForeignKey("sale_order.SaleOrderID"))
    SaleOrderCode=Column(String(100))
    Customer=Column(String(64))
    OrderQuantity=Column(Integer)    
    
    StyleTemplateID=Column(Integer, ForeignKey("style_template.StyleTemplateID"))
    StyleTemplateCode=Column(String(64))   
    FollowsOperationSequence=Column(Boolean)
    
    MarkerMapping=Column(JSON)    
    UpdatedAt=Column(DateTime)  
    CreatedAt=Column(DateTime) 

    production_order = relationship("ProductionOrder")
    sale_order = relationship("SaleOrder")
    style_template = relationship("StyleTemplate")
    marker = relationship("Marker")
    cut_report = relationship("CutReport")
    cut_job = relationship("Cutjob")
    machine = relationship("Machine")
    line = relationship("Line")
    worker = relationship("Worker")    
    worker_scan = relationship("WorkerScan")
    scan = relationship("Scan") 
    piece_wise_cut_report = relationship("PieceWiseCutReport")     
    operation = relationship("Operation")            
    section = relationship("Section")

In [43]:
class Module(Base):
    __tablename__ = 'module'
    __table_args__ = {'extend_existing': True}

    ModuleID=Column(Integer, primary_key = True, autoincrement=False) 
    ModuleCode=Column(String(64))
    UpdatedAt=Column(DateTime)  
    CreatedAt=Column(DateTime)

In [44]:
class StyleBulletin(Base):
    __tablename__ = 'style_bulletin'
    __table_args__ = {'extend_existing': True}

    StyleBulletinID=Column(Integer, primary_key = True, autoincrement=False) 
   
    StyleTemplateID=Column(Integer,ForeignKey("style_template.StyleTemplateID"))
    StyleTemplateCode=Column(String(64))

    OperationID=Column(Integer, ForeignKey("operation.OperationID")) 
    OperationCode=Column(String(64))    
    OperationName =Column(String(64))
    OperationDescription = Column(String(64))    
    Department = Column(String(64))
    PieceRate=Column(Float)      
    OperationType=Column(String(64))
    OperationImageUrl=Column(String(2056))
    OperationThumbnailUrl=Column(String(2056))
    SectionID = Column(Integer, ForeignKey("section.SectionID"))
    SectionCode=Column(String(64))
    SectionDescription=Column(String(64))    

    pieceRate=Column(Float)
    OperationSequence=Column(Integer)    
    ScanType=Column(String(10))
    IsFirst=Column(Boolean)
    IsLast=Column(Boolean)

    MachineTypeID=Column(Integer, ForeignKey("machine_type.MachineTypeID"))
    MachineTypeCode=Column(String(64))
    MachineTypeDescription=Column(String(64))
    Allowance=Column(Float)

    UpdatedAt=Column(DateTime)  
    CreatedAt=Column(DateTime) 

    style_template = relationship("StyleTemplate")
    operation = relationship("Operation")
    section = relationship("Section")
    machine_type = relationship("MachineType")

In [45]:
class Tag(Base):
    __tablename__ = 'tag'
    __table_args__ = {'extend_existing': True}

    TagID=Column(Integer, primary_key = True, autoincrement=False) 
    
    BundleID=Column(Integer, ForeignKey("cut_report.BundleID"))
    BundleCode=Column(String(64))

    BundleQuantity=Column(Integer)
    ScannedQuantity=Column(Integer)
    RemainingQuantity=Column(Integer)
    CutJobID=Column(Integer, ForeignKey("cut_job.CutJobID"))
    CutNo=Column(Integer) 
    CutQuantity=Column(Integer)

    MarkerID=Column(Integer, ForeignKey("marker.MarkerID")) 
    MarkerCode=Column(String(64))    
    ProductionOrderID=Column(Integer, ForeignKey("production_order.ProductionOrderID"))
    ProductionOrderCode=Column(String(64))
    
    SaleOrderID=Column(Integer, ForeignKey("sale_order.SaleOrderID"))
    SaleOrderCode=Column(String(100))
    Customer=Column(String(64))
    OrderQuantity=Column(Integer)    
    
    StyleTemplateID=Column(Integer, ForeignKey("style_template.StyleTemplateID"))
    StyleTemplateCode=Column(String(64))   
    FollowsOperationSequence=Column(Boolean)
    
    MarkerMapping=Column(JSON) 
    UpdatedAt=Column(DateTime)  
    CreatedAt=Column(DateTime) 

    cut_report = relationship("CutReport")
    cut_job = relationship("CutJob")
    marker = relationship("Marker")
    production_order = relationship("ProdcutionOrder")
    sale_order = relationship("SaleOrder")
    style_template = relationship("StyleTemplate")

In [46]:
class User(Base):
    __tablename__ = 'user'
    __table_args__ = {'extend_existing': True}

    UserID=Column(Integer, primary_key = True, autoincrement=False) 
    UserName=Column(String(64))
    Password=Column(String(1024))    
    UserType=Column(String(64))

    LineID=Column(Integer,ForeignKey("line.LineID"))
    LineCode=Column(String(64))
    LineDescription=Column(String(64))

    SectionID=Column(Integer,ForeignKey("section.SectionID")) 
    SectionCode=Column(String(64))
    SectionDescription=Column(String(64))

    UpdatedAt=Column(DateTime)  
    CreatedAt=Column(DateTime) 

    line = relationship("Line")
    section = relationship("Section")

In [47]:
class UserPermission(Base):
    __tablename__ = 'userpersmission'
    __table_args__ = {'extend_existing': True}

    UserPermissionID=Column(Integer, primary_key = True, autoincrement=False) 

    UserID=Column(Integer,ForeignKey("user.UserID")) 
    ModuleID=Column(Integer, ForeignKey("module.ModuleID"))    
    
    ModuleCode=Column(String(64))

    UserName=Column(String(64))
    Password=Column(String(1024))    
    UserType=Column(String(64))
    LineID=Column(Integer,ForeignKey("line.LineID"))
    LineCode=Column(String(64))
    LineDescription=Column(String(64))
    SectionID=Column(Integer,ForeignKey("section.SectionID")) 
    SectionCode=Column(String(64))
    SectionDescription=Column(String(64))

    UpdatedAt=Column(DateTime)  
    CreatedAt=Column(DateTime) 

    user = relationship("User")
    module = relationship("Module")
    line = relationship("Line")
    section = relationship("Section")

### Creating tables in postgres

In [48]:
Base.metadata.create_all(engine_postgres)